CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL,
	enabled BOOL NOT NULL DEFAULT False,
	email VARCHAR(128),
	PRIMARY KEY (username),
	UNIQUE (username)
);

CREATE TABLE roles (
	username VARCHAR(128) NOT NULL,
	role VARCHAR(128) NOT NULL DEFAULT 'ROLE_USER',
	FOREIGN KEY (username) REFERENCES users(username)
);