CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	nickname VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL,
	firstname VARCHAR(128) NOT NULL,
	lastname VARCHAR(128)
	enabled BOOL NOT NULL DEFAULT False,
	email VARCHAR(128),
	PRIMARY KEY (id),
	UNIQUE (nickname)
);

CREATE TABLE roles (
	id INT NOT NULL AUTO_INCREMENT,
	role VARCHAR(128) NOT NULL DEFAULT 'ROLE_USER',
	uid INT, PRIMARY KEY (id),
 	FOREIGN KEY (uid) REFERENCES users(id),
	UNIQUE (id)
);

CREATE TABLE logs (
	id INT NOT NULL AUTO_INCREMENT,
    date TIMESTAMP,
    logger VARCHAR(100),
    level VARCHAR(100),
    message TEXT,
    exception TEXT,
    PRIMARY KEY (id)
);